export type ContentFaction = 'mech' | 'bugs'
export type ContentProducer = 'base' | 'factory' | 'airfield' | 'seaFactory'
export type StructureFamily = 'turret' | 'extractor' | 'radar' | 'repair' | 'factory' | 'airfield' | 'seaFactory'

export const ADDITIONAL_UNIT_CONTENT = [
  { role: 'aaBeamGunship', label: '光束防空炮艇', ini: 'aa_beam_gunship/aa_beam_gunship.ini', image: 'aa_beam_gunship/base3.png', deadImage: 'aa_beam_gunship/base3_dead.png', producer: 'airfield', faction: 'mech', flying: true },
  { role: 'aaBeamGunshipAfterburn', label: '光束炮艇·加力', ini: 'aa_beam_gunship/aa_beam_gunship_afterburn.ini', image: 'aa_beam_gunship/base3.png', deadImage: 'aa_beam_gunship/base3_dead.png', producer: 'airfield', faction: 'mech', flying: true },
  { role: 'amphibiousJet', label: '两栖喷气机', ini: 'amphibious_jet/amphibious_jet.ini', image: 'amphibious_jet/amphibious_jet.png', deadImage: 'amphibious_jet/amphibious_jet_dead.png', producer: 'airfield', faction: 'mech', flying: true },
  { role: 'amphibiousJetTransition', label: '两栖喷气机·转换', ini: 'amphibious_jet/amphibious_jet_transition.ini', image: 'amphibious_jet/amphibious_jet.png', deadImage: 'amphibious_jet/amphibious_jet_dead.png', producer: 'airfield', faction: 'mech', flying: true },
  { role: 'amphibiousJetUnderwater', label: '两栖喷气机·水下', ini: 'amphibious_jet/amphibious_jet_underwater.ini', image: 'amphibious_jet/amphibious_jet.png', deadImage: 'amphibious_jet/amphibious_jet_dead.png', producer: 'seaFactory', faction: 'mech', flying: false, water: true },
  { role: 'experimentalCarrier', label: '实验航母', ini: 'experimental_carrier/Experiemental_carrier.ini', image: 'experimental_carrier/Experiemental_carrier.png', deadImage: 'experimental_carrier/Experiemental_carrier_dead.png', producer: 'seaFactory', faction: 'mech', water: true, builder: true },
  { role: 'experimentalDropship', label: '实验运输艇', ini: 'experimental_dropship/experimental_dropship.ini', image: 'experimental_dropship/experimental_dropship.png', deadImage: 'experimental_dropship/experimental_dropship_dead.png', producer: 'airfield', faction: 'mech', flying: true },
  { role: 'experimentalGunship', label: '实验炮艇', ini: 'experimental_gunship/experimental_gunship.ini', image: 'experimental_gunship/body.png', deadImage: 'experimental_gunship/body_dead.png', producer: 'airfield', faction: 'mech', flying: true },
  { role: 'experimentalGunshipLanded', label: '实验炮艇·着陆', ini: 'experimental_gunship/experimental_gunship_landed.ini', image: 'experimental_gunship/body.png', deadImage: 'experimental_gunship/body_dead.png', producer: 'factory', faction: 'mech', flying: false },
  { role: 'experimentalSpider', label: '实验蜘蛛', ini: 'experimental_spider/experimental_spider.ini', image: 'experimental_spider/body.png', deadImage: 'experimental_spider/body_dead.png', producer: 'factory', faction: 'mech' },
  { role: 'heavySub', label: '重型潜艇', ini: 'heavy_sub/heavy_sub.ini', image: 'heavy_sub/base.png', deadImage: 'heavy_sub/base_dead.png', producer: 'seaFactory', faction: 'mech', water: true },
  { role: 'mechEngineer', label: '机甲工程师', ini: 'mech_engineer/mech_engineer.ini', image: 'mech_engineer/body.png', deadImage: 'mech_engineer/body_dead.png', producer: 'base', faction: 'mech', builder: true },
  { role: 'mechArtillery', label: '机甲火炮', ini: 'mechs_large/mech_artillery.ini', image: 'mechs_large/topArtillery.png', producer: 'factory', faction: 'mech' },
  { role: 'mechBunker', label: '机甲堡垒', ini: 'mechs_large/mech_bunker.ini', image: 'mechs_large/topBunker.png', deadImage: 'mechs_large/topBunkerDead.png', producer: 'factory', faction: 'mech' },
  { role: 'mechBunkerDeployed', label: '机甲堡垒·部署', ini: 'mechs_large/mech_bunker_deployed.ini', image: 'mechs_large/topBunker.png', deadImage: 'mechs_large/topBunkerDead.png', producer: 'factory', faction: 'mech' },
  { role: 'mechFlame', label: '火焰机甲', ini: 'mechs_large/mech_flame.ini', image: 'mechs_large/topFlame.png', producer: 'factory', faction: 'mech' },
  { role: 'mechFlyingLanded', label: '飞行机甲·着陆', ini: 'mechs_large/mech_flying_landed.ini', image: 'mechs_large/topFlying.png', producer: 'factory', faction: 'mech' },
  { role: 'mechFlyingTakeoff', label: '飞行机甲·起飞', ini: 'mechs_large/mech_flying_takeoff.ini', image: 'mechs_large/topFlying.png', producer: 'airfield', faction: 'mech', flying: true },
  { role: 'mechHeavyMissile', label: '重导弹机甲', ini: 'mechs_large/mech_heavyMissile.ini', image: 'mechs_large/topHeavyMissile.png', producer: 'factory', faction: 'mech' },
  { role: 'mechLaser', label: '激光机甲', ini: 'mechs_large/mech_laser.ini', image: 'mechs_large/topLaser.png', producer: 'factory', faction: 'mech' },
  { role: 'mechLightning', label: '闪电机甲', ini: 'mechs_large/mech_lightning.ini', image: 'mechs_large/topLightning.png', producer: 'factory', faction: 'mech' },
  { role: 'mechMinigun', label: '机枪机甲', ini: 'mechs_large/mech_minigun.ini', image: 'mechs_large/topMinigun.png', producer: 'factory', faction: 'mech' },
  { role: 'mechGun', label: '轻型机甲', ini: 'mechs_small/mech_gun.ini', image: 'mechs_small/topGun.png', producer: 'factory', faction: 'mech' },
  { role: 'mechMissile', label: '轻型导弹机甲', ini: 'mechs_small/mech_missile.ini', image: 'mechs_small/topMissile.png', producer: 'factory', faction: 'mech' },
  { role: 'missileAirship', label: '导弹飞艇', ini: 'missile_airship/missile_airship.ini', image: 'missile_airship/body.png', deadImage: 'missile_airship/body_dead.png', producer: 'airfield', faction: 'mech', flying: true },
  { role: 'modularSpider', label: '模块蜘蛛', ini: 'modular_spider/modular_spider.ini', image: 'modular_spider/body.png', deadImage: 'modular_spider/body_dead.png', producer: 'factory', faction: 'mech', builder: true },
  { role: 'nautilusSubmarine', label: '鹦鹉螺潜艇', ini: 'nautilus/nautilus.ini', image: 'nautilus/body.png', deadImage: 'nautilus/body_dead.png', producer: 'seaFactory', faction: 'mech', water: true },
  { role: 'nautilusSubmarineLand', label: '鹦鹉螺·陆行', ini: 'nautilus/nautilusLand.ini', image: 'nautilus/body.png', deadImage: 'nautilus/body_dead.png', producer: 'factory', faction: 'mech' },
  { role: 'nautilusSubmarineSurface', label: '鹦鹉螺·水面', ini: 'nautilus/nautilusSurface.ini', image: 'nautilus/body2.png', deadImage: 'nautilus/body_dead.png', producer: 'seaFactory', faction: 'mech', water: true },
  { role: 'robotCrab', label: '侦察机器人蟹', ini: 'nautilus/robotCrab/robotCrab.ini', image: 'nautilus/robotCrab/base.png', deadImage: 'nautilus/robotCrab/base_dead.png', producer: 'factory', faction: 'mech' },
  { role: 'robotCrabWater', label: '水行机器人蟹', ini: 'nautilus/robotCrab/robotCrabWater.ini', image: 'nautilus/robotCrab/base.png', deadImage: 'nautilus/robotCrab/base_dead.png', producer: 'seaFactory', faction: 'mech', water: true },
  { role: 'classicTank', label: '经典坦克', ini: 'tanks/tank.ini', image: 'tanks/tank.png', deadImage: 'tanks/tank_dead.png', producer: 'factory', faction: 'mech' },
  { role: 'bugMeleeT31', label: '虫族重型近战', ini: 'bug_melee/bug_melee_t31.ini', image: 'bug_melee/bug_meleet31.png', deadImage: 'bug_melee/bug_meleet31_dead.png', producer: 'base', faction: 'bugs', builder: true, frameWidth: 80, frameHeight: 85, frameCount: 6 },
  { role: 'bugBee', label: '虫蜂', ini: 'classic_bugs/bug_bee/bug_bee.ini', image: 'classic_bugs/bug_bee/bug_bee.png', producer: 'airfield', faction: 'bugs', flying: true, frameWidth: 28, frameHeight: 26, frameCount: 2 },
  { role: 'bugFly', label: '飞虫', ini: 'classic_bugs/bug_fly/bug_fly.ini', image: 'classic_bugs/bug_fly/bug_fly.png', producer: 'airfield', faction: 'bugs', flying: true, frameWidth: 32, frameHeight: 24, frameCount: 2 },
  { role: 'bugMelee', label: '近战虫', ini: 'classic_bugs/bug_melee/bug_melee.ini', image: 'classic_bugs/bug_melee/bug_melee.png', deadImage: 'classic_bugs/bug_melee/bug_dead.png', producer: 'factory', faction: 'bugs', frameWidth: 21, frameHeight: 27, frameCount: 5 },
  { role: 'bugMeleeLarge', label: '大型近战虫', ini: 'classic_bugs/bug_melee/bug_melee_large.ini', image: 'classic_bugs/bug_melee/bug_melee.png', deadImage: 'classic_bugs/bug_melee/bug_dead.png', producer: 'factory', faction: 'bugs', frameWidth: 21, frameHeight: 27, frameCount: 5 },
  { role: 'bugMeleeSmall', label: '小型近战虫', ini: 'classic_bugs/bug_melee/bug_melee_small.ini', image: 'classic_bugs/bug_melee/bug_melee.png', deadImage: 'classic_bugs/bug_melee/bug_dead.png', producer: 'factory', faction: 'bugs', frameWidth: 21, frameHeight: 27, frameCount: 5 },
  { role: 'bugRanged', label: '远程虫', ini: 'classic_bugs/bug_ranged/bug_ranged.ini', image: 'classic_bugs/bug_ranged/bug_ranged.png', producer: 'factory', faction: 'bugs', frameWidth: 21, frameHeight: 42, frameCount: 6 },
  { role: 'bugSpore', label: '孢子虫', ini: 'classic_bugs/bug_spore/bug_spore.ini', image: 'classic_bugs/bug_spore/bug_spore.png', producer: 'factory', faction: 'bugs', frameWidth: 21, frameHeight: 27, frameCount: 3 },
  { role: 'bugPickup', label: '虫族拾荒者', ini: 'classic_bugs/bugs/bug_pickup.ini', image: 'classic_bugs/bugs/bug_pickup.png', producer: 'factory', faction: 'bugs', frameWidth: 26, frameHeight: 40, frameCount: 2 },
  { role: 'bugWasp', label: '虫族黄蜂', ini: 'classic_bugs/bugs/bug_wasp.ini', image: 'classic_bugs/bugs/bug_wasp.png', producer: 'airfield', faction: 'bugs', flying: true, frameWidth: 26, frameHeight: 40, frameCount: 2 },
  { role: 'bugRangedT2', label: '远程虫 T2', ini: 'classic_bugs/bugs_t2/bug_ranged_t2.ini', image: 'classic_bugs/bugs_t2/bug_ranged_t2.png', producer: 'factory', faction: 'bugs', frameWidth: 23, frameHeight: 67, frameCount: 1 },
] as const

export const ADDITIONAL_STRUCTURE_CONTENT = [
  { kind: 'extractorT2', label: '采集器 T2', family: 'extractor', ini: ['extractor/extractor_common.ini', 'extractor/extractorT2.ini'], body: 'extractor/extractor_t2.png', back: 'extractor/extractor_back.png' },
  { kind: 'extractorT3', label: '采集器 T3', family: 'extractor', ini: ['extractor/extractor_common.ini', 'extractor/extractorT3.ini'], body: 'extractor/extractor_t3.png', back: 'extractor/extractor_back.png' },
  { kind: 'extractorT3Overclocked', label: '采集器 T3·超频', family: 'extractor', ini: ['extractor/extractor_common.ini', 'extractor/extractorT3_overclocked.ini'], body: 'extractor/extractor_t3_overclocked.png', back: 'extractor/extractor_back.png' },
  { kind: 'extractorT3Reinforced', label: '采集器 T3·强化', family: 'extractor', ini: ['extractor/extractor_common.ini', 'extractor/extractorT3_reinforced.ini'], body: 'extractor/extractor_t3_reinforced.png', back: 'extractor/extractor_back.png' },
  { kind: 'fabricatorT1', label: '维修站 T1', family: 'repair', ini: ['fabricator/fabricatorT1.ini'], body: 'fabricator/fabricatorT1.png' },
  { kind: 'fabricatorT2', label: '维修站 T2', family: 'repair', ini: ['fabricator/fabricatorT2.ini'], body: 'fabricator/fabricatorT2.png' },
  { kind: 'fabricatorT3', label: '维修站 T3', family: 'repair', ini: ['fabricator/fabricatorT3.ini'], body: 'fabricator/fabricatorT3.png' },
  { kind: 'factoryT2', label: '机甲工厂 T2', family: 'factory', ini: ['mech_factory/mechFactoryT2.ini'], body: 'mech_factory/mechFactoryTopT2.png', back: 'mech_factory/mechFactoryBottom.png', door: 'mech_factory/mechFactoryDoor.png' },
  { kind: 'radarT1', label: '前哨站 T1', family: 'radar', ini: ['outpost/outpost.ini'], body: 'outpost/outpost.png', turret: 'turrets/radar.png' },
  { kind: 'radarT2', label: '前哨站 T2', family: 'radar', ini: ['outpost/outpostT2.ini'], body: 'outpost/outpost.png', turret: 'turrets/radar.png' },
  { kind: 'turretAntiAir', label: '防空炮塔', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_antiair.ini'], body: 'turrets/turret_base.png', turret: 'turrets/anti_air_top.png' },
  { kind: 'turretAntiAirFlak', label: '防空高射炮', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_antiair_flakgun.ini'], body: 'turrets/turret_base.png', turret: 'turrets/anti_air_top_flakgun.png' },
  { kind: 'turretAntiAirT2', label: '防空炮塔 T2', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_antiair_t2.ini'], body: 'turrets/turret_base2.png', turret: 'turrets/anti_air_top_l2.png' },
  { kind: 'turretAntiAirT3', label: '防空炮塔 T3', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_antiair_t3.ini'], body: 'turrets/turret_base2B.png', turret: 'turrets/anti_air_top_l3.png' },
  { kind: 'turretT1Artillery', label: '火炮塔 T1', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_t1_artillery.ini'], body: 'turrets/turret_base.png', turret: 'turrets/turret_top_artillery.png' },
  { kind: 'turretT1Lightning', label: '闪电塔 T1', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_t1_lightning.ini'], body: 'turrets/turret_base.png', turret: 'turrets/turret_top_lightning.png' },
  { kind: 'turretT2Artillery', label: '火炮塔 T2', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_t2_artillery.ini'], body: 'turrets/turret_base2.png', turret: 'turrets/turret_top_artillery_l2.png' },
  { kind: 'turretT2Flame', label: '火焰塔 T2', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_t2_flame.ini'], body: 'turrets/turret_base2.png', turret: 'turrets/turret_top_flame.png' },
  { kind: 'turretT2Gun', label: '机枪塔 T2', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_t2_gun.ini'], body: 'turrets/turret_base2.png', turret: 'turrets/turret_top_l2.png' },
  { kind: 'turretT2Lightning', label: '闪电塔 T2', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_t2_lightning.ini'], body: 'turrets/turret_base2.png', turret: 'turrets/turret_top_lightning_l2.png' },
  { kind: 'turretT3Gun', label: '机枪塔 T3', family: 'turret', ini: ['turrets/turret_common_land.ini', 'turrets/turret_t3_gun.ini'], body: 'turrets/turret_base2B.png', turret: 'turrets/turret_top_l3.png' },
  { kind: 'nukeLauncher', label: '核导弹发射井', family: 'turret', ini: ['nukes/nuke_launcher.ini'], body: 'nukes/nuke_launcher_front.png', back: 'nukes/nuke_launcher_back.png' },
  { kind: 'antiNukeLauncher', label: '反核拦截井', family: 'turret', ini: ['nukes/antinuke_launcher.ini'], body: 'nukes/antinuke_launcher_front.png', back: 'nukes/antinuke_launcher_back.png' },
  { kind: 'bugBaseGenerator', label: '虫族孵化器', family: 'factory', ini: ['bug_base/bug_generator/bug_generator.ini'], body: 'bug_base/bug_generator/bug_generator.png' },
  { kind: 'bugBaseGeneratorT2', label: '虫族孵化器 T2', family: 'factory', ini: ['bug_base/bug_generator/bug_generatorT2.ini'], body: 'bug_base/bug_generator/bug_generator2.png' },
  { kind: 'bugExtractor', label: '虫族采集器', family: 'extractor', ini: ['classic_bugs/bug_extractor/bug_extractor.ini'], body: 'classic_bugs/bug_extractor/bug_extractor.png' },
  { kind: 'bugExtractorT2', label: '虫族采集器 T2', family: 'extractor', ini: ['classic_bugs/bug_extractor/bug_extractorT2.ini'], body: 'classic_bugs/bug_extractor/bug_extractor.png' },
  { kind: 'bugGenerator', label: '经典虫族孵化器', family: 'factory', ini: ['classic_bugs/bug_generator/bug_generator.ini'], body: 'classic_bugs/bug_generator/bug_generator.png' },
  { kind: 'bugGeneratorT2', label: '经典虫族孵化器 T2', family: 'factory', ini: ['classic_bugs/bug_generator/bug_generatorT2.ini'], body: 'classic_bugs/bug_generator/bug_generator.png' },
  { kind: 'bugNest', label: '虫巢', family: 'factory', ini: ['classic_bugs/bug_nest/bug_nest.ini'], body: 'classic_bugs/bug_nest/bug_nest_front.png', back: 'classic_bugs/bug_nest/bug_nest_back.png' },
  { kind: 'bugTurret', label: '虫族炮塔', family: 'turret', ini: ['classic_bugs/bug_turret/bug_turret.ini'], body: 'classic_bugs/bug_turret/bug_turret.png' },
] as const

export type AdditionalUnitRole = typeof ADDITIONAL_UNIT_CONTENT[number]['role']
export type AdditionalStructureKind = typeof ADDITIONAL_STRUCTURE_CONTENT[number]['kind']

export const BASE_STRUCTURE_CONTENT = [
  { kind: 'headquarters', label: '实验室总部', ini: 'laboratory/laboratory.ini', body: 'laboratory/base.png', deadImage: 'laboratory/base_dead.png' },
] as const

export const CONTENT_EXCLUDED_AS_NON_ENTITIES = [
  'extractor/extractor_common.ini',
  'mechs_large/mech_large_common.ini',
  'mechs_large/mech_med_common.ini',
  'mechs_small/mechs_small_common.ini',
  'modular_spider/common_slot.ini',
  'modular_spider/common_weapon_slot.ini',
  'modular_spider/baseSlot.ini',
  'modular_spider/emptySlot.ini',
  'modular_spider/modular_spider_nonEmpty.ini',
  'modular_spider/antiair.ini',
  'modular_spider/antiairFlak.ini',
  'modular_spider/antiairT2.ini',
  'modular_spider/antinuke.ini',
  'modular_spider/artillery.ini',
  'modular_spider/blink.ini',
  'modular_spider/fabricator.ini',
  'modular_spider/fabricatorT2.ini',
  'modular_spider/gunturret.ini',
  'modular_spider/gunturretT2.ini',
  'modular_spider/laser_defense.ini',
  'modular_spider/lightning.ini',
  'modular_spider/shieldGen.ini',
  'modular_spider/smallgun.ini',
  'modular_spider/smallgunT2.ini',
  'modular_spider/speed.ini',
  'modular_spider/speed_incomplete.ini',
  'missing_unit/missing.ini',
  'miscellaneous/example_faction_picker.ini',
  'miscellaneous/flare_10s.ini',
  'resource_deposits/creditsCrate.ini',
  'resource_deposits/crystal_mid.ini',
] as const
